name: "Deploy to Production"

permissions:
  contents: read
  
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        run: echo "I am deployed now"
